#!/bin/bash

echo "Programmation du Service Tacheron en cours";

cp ./daemon_tacheron.sh /usr/sbin/daemon_tacheron.sh; #permet de placer le script dans le dossier des services systèmes

cp ./creation_skeleton.sh /etc/init.d/daemon_tacheron.sh; #permet de configurer le service demons

chmod +x /etc/init.d/daemon_tacheron.sh; #rend exécutable le fichier de configuration

update-rc.d daemon_tacheron.sh defaults 2>/dev/null; #permet l'ajout du service au démarrage du système

/etc/init.d/daemon_tacheron.sh start 2>/dev/null; #démarre le service

echo "Programmation du Service Tacheron terminé";






