#!/bin/bash

echo "Programmation du Démons en cours";

cp ./daemon_tacheron.sh /usr/sbin/daemon_tacheron.sh;

cp ./creation_skeleton.sh /etc/init.d/daemon_tacheron.sh;

chmod +x /etc/init.d/daemon_tacheron.sh;

update-rc.d daemon_tacheron.sh defaults;

/etc/init.d/daemon_tacheron.sh start;

echo "Programmation du Démons terminé";


