#!/bin/bash

#projet lo14

erreur_saisie()
{
    echo "mauvais argument(s) pour tacheron"
    echo "help pour plus d'information"
    exit 0
}

erreur_fichier_inexistant()
{
    echo "le fichier $1 est inexistant"
    exit 0
}

help_user()
{
    echo "user - specifie un utilisateur particulier"
    echo "--user [USER_NAME]"
    echo "-u [USER_NAME]"
}

help_affiche()
{
    echo "aff - affiche le fichier tacherontab"
    echo "--aff"
    echo "-l" 
}

help_remove()
{
    echo "rem - efface le fichier tacherontab"
    echo "--rem"
    echo "-r" 
}

help_edite()
{
    echo "edit - édite le fichier tacherontab dans vi"
    echo "--edit"
    echo "-e"
}


help()
{
    echo "NAME"
    echo "Tacheron - planifier des taches"
    echo "SYNOPSIS"
    echo "tacheron [OPTION] [COMMANDE]"
    echo "DESCRIPTION"
    help_user()
    help_affiche()
    help_remove()
    help_edite()
    help_edite()
    echo "Planifier une tache"
    echo "[SECONDE][MINUTE][HEURES][JOUR DU MOIS][MOIS DE L'ANNEE][JOUR DE LA SEMAINE][COMMANDE]"
}

verifier_tacherontab()
{
    if [ -d $1 ]
    then
        return true
    else
        return false
    fi
}

if [ $# -eq 1 ]
then 
    if [ $1 = "help" ]
    then
        help()
    elif [ $1 = "-l" ] || [ $1 = "--aff" ]
    then
        if verifier_tacherontab() "/etc/tacherontab"
        then
            cat  /etc/tacherontab
        else
            erreur_fichier_inexistant "/etc/tacherontab"
        fi
    elif [ $1 = "-r" ] || [ $1 = "--rem" ]
    then
        if verifier_tacherontab() "/etc/tacherontab"
        then
            rm  /etc/tacherontab
        else
            erreur_fichier_inexistant "/etc/tacherontab"
        fi
    elif [ $1 = "-e"  ] || [ $1 = "--edit" ]
    then
        if verifier_tacherontab() "/etc/tacherontab"
        then
            vi  /etc/tacherontab
        else
            erreur_fichier_inexistant "/etc/tacherontab"
        fi
    else
        erreur_saisie()
    fi  
elif [ $# -eq 2 ]
then
    if [ $1 = "help" ]
    then
        if [ $2 = "-l" ] || [ $2 = "--aff" ]
        then
            help_affiche
        elif [ $2 = "-e" ] || [ $2 = "--edit" ]
        then 
            help_edite
        elif [ $2 = "-r" ] || [ $2 = "--rem" ]
            help_remove
        else
            erreur_saisie
        fi
    else
       erreur_saisie
    fi
elif [ $# -eq 3 ]
then
    if [ $1 = "--user" ] || [ $1 = "-u" ]
    then
        cat /etc/passwd | cut -d ":" -f 1 > temp
        userTemp = grep -c ^$2$ temp

        if [ $userTemp -eq 1 ]
        then 
            if [ $1 = "-l" ] || [ $1 = "--aff" ]
            then
                if verifier_tacherontab() "/etc/tacherontab$2"
                then
                    cat  /etc/tacherontab
                else
                    erreur_fichier_inexistant "/etc/tacherontab$2"
                fi
            elif [ $1 = "-r" ] || [ $1 = "--rem" ]
            then
                if verifier_tacherontab() "/etc/tacherontab$2"
                then
                    rm  /etc/tacherontab
                else
                    erreur_fichier_inexistant "/etc/tacherontab$2"
                fi
            elif [ $1 = "-e"  ] || [ $1 = "--edit" ]
            then
                if verifier_tacherontab() "/etc/tacherontab$2"
                then
                    vi  /etc/tacherontab
                else
                    erreur_fichier_inexistant "/etc/tacherontab$2"
                fi
            else
                erreur_saisie()
            fi
        else
           erreur_saisie()
        fi
    else
        erreur_saisie()
    fi
elif [ $# -eq 7 ]
then
    
else
   erreur_saisie()
fi 


