#!/bin/bash

transformation_argument()
{
    #on met tous les files et rep du dossier courant dans un fichier temp et on compte le nombre d'occurence
    for i in `echo * | tr " " " "`
    do 
        echo $i >> temp
    done
    compteurls=$(cat temp | wc -l)
    #compteur utilise pour savoir si il faut ajouter a temp2 ou pas
    let "compteur = 0"
    let "compteurUser = 0"
    for i in "$@"
    do
        if [ $i = "-u" ] ||[ $i = "--user" ]
        then
            let "compteurUser = compteurUser + 1"
        else
            if [ $compteurUser -ne 1 ]
            then
                echo "0" > estDedans
                while read ligne
                do
                    if [ $ligne = $i ]
                    then
                        
                        echo "1" > estDedans
                        let "compteur = compteur + 1"
                        echo "$1" >> temp3
                        break
                    fi
                done < temp

                result=$(head -n 1 estDedans)
                if [ $result -eq 0 ]
                then
                    if [ $compteur -gt 0 ] && [ $compteur -lt $compteurls ]
                    then
                        cat temp3 | while read ligne
                                    do
                                        echo "$ligne" >> temp2
                                    done
                        
                        let "compteur = 0"
                        rm temp3
                    fi
                    echo "$i" >> temp2
                fi

                if [ $compteur -eq $compteurls ]
                then
                    echo "*" >> temp2
                    let "compteur = 0"
                    rm temp3
                fi
            else
                let "compteurUser = 0"
            fi
        fi
    done

    let "compteur = 1"
    result=$(whoami)
    while read ligne
    do
        if [ $compteur -eq 7 ]
        then
            result="$result \"$ligne"
        else
            result="$result $ligne"
        fi
        let "compteur = compteur + 1"
    done < temp2
    result="$result\""
    rm temp2
    rm temp
    rm estDedans
    echo "$result"
}

ola=$(transformation_argument $@)
echo "$ola"