#!/bin/bash

verifier_tacherontab()
{
    if [ -e "$1" ]
    then
        echo "true"
    else
        echo "false"
    fi
}



if [ $(verifier_tacherontab "/etc/tacherontab") = "true" ]
then
    cat  /etc/tacherontab
else
    echo "erreur"
fi